# Generated by Django 2.2.4 on 2019-10-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprices',
            name='description',
            field=models.CharField(default='read all articles', max_length=100),
            preserve_default=False,
        ),
    ]
