# Generated by Django 2.2.4 on 2021-01-02 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='actual_score',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='prediction',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prediction',
            name='match_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='goals_fulltime',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='goals_halftime',
            field=models.CharField(max_length=5),
        ),
    ]
