# Generated by Django 2.2.4 on 2021-01-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210102_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
    ]
